id: A5BA74F32
title: 'The Blissful Path to Awakening: A Guru Yoga'
type: translation
pechas:
- I344C33B3
- IB3BD64A7
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:13:15.537861
  last_modified_at: 2023-01-04 12:13:15.537870
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I344C33B3/6C35: 6D6E
  IB3BD64A7/8773: 6D6E
